import { EmptyState } from '../components/EmptyState';
import { ErrorState } from '../components/ErrorState';
import { MetricCard } from '../components/MetricCard';
import { ProductionShell } from '../components/ProductionShell';
import { StatusBadge, type StatusTone } from '../components/StatusBadge';
import { fetchV5LiveAlphaBufferStatus, fetchV5LiveAlphaLatestSignals, fetchV5LiveAlphaStatus, fetchV5LiveAlphaSummary } from '../lib/apiClient';

const fallback = {
  mode: 'mock_live',
  symbols: ['AAPL', 'MSFT', 'NVDA', 'SPY', 'QQQ'],
  alpha_signal_driven: true,
  paper_trading: true,
  real_trading: false,
  broker_connected: false,
  real_money_enabled: false,
};

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
}

function asList(value: unknown): unknown[] {
  return Array.isArray(value) ? value : [];
}

function tone(value: unknown): StatusTone {
  const text = String(value ?? '').toLowerCase();
  if (text.includes('fail') || text.includes('error')) return 'Error';
  if (text.includes('warning') || text.includes('hold') || text.includes('degraded')) return 'Warning';
  return 'OK';
}

export default async function V5LiveAlphaPage() {
  const [statusResult, signalsResult, summaryResult, bufferResult] = await Promise.all([
    fetchV5LiveAlphaStatus(),
    fetchV5LiveAlphaLatestSignals(),
    fetchV5LiveAlphaSummary(),
    fetchV5LiveAlphaBufferStatus(),
  ]);
  const status = { ...fallback, ...asRecord(asRecord(statusResult.data).live_alpha) };
  const summary = asRecord(summaryResult.data?.summary);
  const signals = asList(signalsResult.data?.signals ?? summary.latest_signals);
  const bufferStatus = asRecord(bufferResult.data?.buffer_status ?? summary.buffer_status);
  const warnings = asList(summary.warnings);
  const errors = asList(summary.errors);

  return (
    <ProductionShell
      title="V5 Live Alpha"
      eyebrow="Alpha Signal Integration"
      description="V5 alpha signal adapter drives paper orders from live feature windows. Execution remains simulated."
      activePath="/v5-live-alpha"
    >
      {!statusResult.ok ? <ErrorState description={statusResult.errorMessage ?? 'Backend unavailable. Showing safe live alpha fallback state.'} /> : null}
      <div className="summaryStrip">
        <MetricCard title="Live Alpha Paper Status" value={String(summary.health_status ?? 'HEALTHY')} description="Alpha signal driven paper trading" status={tone(summary.health_status)} />
        <MetricCard title="Signals" value={String(summary.signals_generated ?? signals.length)} description="Latest V5 alpha signal count." />
        <MetricCard title="Orders Filled" value={String(summary.orders_filled ?? 0)} description="Paper fills only, no broker connection." />
      </div>
      <section className="card">
        <div className="cardHeader">
          <h2>Safety Boundary</h2>
          <StatusBadge status="Warning" />
        </div>
        <p>Alpha signal driven paper trading</p>
        <p>Paper trading only</p>
        <p>Real trading: disabled</p>
        <p>Broker: not connected</p>
        <p>Real money: disabled</p>
      </section>
      <div className="grid">
        <MetricCard title="Feature Buffer Readiness" value={String(Object.keys(asRecord(bufferStatus.ready)).length)} description="Symbols with live feature windows." />
        <MetricCard title="BUY / SELL / HOLD" value={`${summary.buy_signals ?? 0} / ${summary.sell_signals ?? 0} / ${summary.hold_signals ?? 0}`} description="Signal counts from V5 alpha adapter." />
        <MetricCard title="Paper Orders" value={`${summary.orders_submitted ?? 0} submitted`} description="Generated by SignalToOrderConverter after alpha signal." />
        <MetricCard title="Portfolio Summary" value={String(summary.final_equity ?? 0)} description="Paper account equity only." />
        <MetricCard title="Risk Status" value="Pre-trade gate" description="Risk gate runs before paper execution." status="OK" />
        <MetricCard title="Warnings / Errors" value={`${warnings.length} / ${errors.length}`} description="Live alpha diagnostics." status={errors.length ? 'Error' : warnings.length ? 'Warning' : 'OK'} />
      </div>
      <div className="grid">
        <section className="card moduleCard">
          <div className="cardHeader">
            <h2>Latest Signals</h2>
            <StatusBadge status={signals.length ? 'OK' : 'Warning'} />
          </div>
          {signals.length ? <pre className="codeBlock">{JSON.stringify(signals.slice(0, 12), null, 2)}</pre> : <EmptyState title="No signals loaded" description="The page can render safely before the backend is available." />}
        </section>
        <section className="card moduleCard">
          <div className="cardHeader">
            <h2>Health Status</h2>
            <StatusBadge status={tone(summary.health_status)} />
          </div>
          <pre className="codeBlock">{JSON.stringify({ status, bufferStatus, warnings, errors }, null, 2)}</pre>
        </section>
      </div>
    </ProductionShell>
  );
}
