from __future__ import annotations


CATEGORIES = [
    "新手推荐",
    "稳健收益",
    "小市值策略",
    "红利低波策略",
    "低估值策略",
    "动量趋势策略",
    "行业轮动策略",
    "指数增强策略",
]


CATALOG = [
    {
        "strategy_id": "small_cap_momentum",
        "name": "small_cap_momentum",
        "display_name": "小市值动量策略",
        "short_description": "寻找近期表现较强的小市值股票，用模拟组合观察趋势延续。",
        "beginner_explanation": "它像是在一组小公司里挑近期更有活力的标的，但只用于回测和模拟交易。",
        "category": "小市值策略",
        "risk_level": "medium",
        "suitable_market": "liquidity_driven",
        "suitable_user": "advanced",
        "strategy_type": "momentum",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["小市值", "动量", "趋势", "进阶"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "ma_crossover",
        "name": "ma_crossover",
        "display_name": "双均线策略",
        "short_description": "用快慢均线判断趋势方向，适合学习策略信号的基本逻辑。",
        "beginner_explanation": "短期均线强于长期均线时偏积极，反之更谨慎。",
        "category": "新手推荐",
        "risk_level": "medium",
        "suitable_market": "bull",
        "suitable_user": "beginner",
        "strategy_type": "momentum",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["新手", "趋势", "均线"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "bank_rotation",
        "name": "bank_rotation",
        "display_name": "银行股轮动策略",
        "short_description": "在银行板块内部做稳健轮动，关注低波动和防御属性。",
        "beginner_explanation": "适合想看稳健板块轮动的人，收益想象空间较低但风险也更平缓。",
        "category": "稳健收益",
        "risk_level": "low",
        "suitable_market": "bear",
        "suitable_user": "steady",
        "strategy_type": "value",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["银行", "稳健", "低波"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "low_valuation_select",
        "name": "low_valuation_select",
        "display_name": "低估值精选股策略",
        "short_description": "优先观察估值较低、基本面更稳的股票池。",
        "beginner_explanation": "它更像是用便宜和稳健两个条件先做筛选，不追求短期爆发。",
        "category": "低估值策略",
        "risk_level": "medium",
        "suitable_market": "sideways",
        "suitable_user": "steady",
        "strategy_type": "value",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["低估值", "稳健", "精选"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "dividend_low_vol",
        "name": "dividend_low_vol",
        "display_name": "红利低波策略",
        "short_description": "偏向高分红、低波动资产，适合更稳健的观察方式。",
        "beginner_explanation": "它偏防守，追求更平滑的模拟收益体验。",
        "category": "红利低波策略",
        "risk_level": "low",
        "suitable_market": "sideways",
        "suitable_user": "beginner",
        "strategy_type": "dividend",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["红利", "低波", "新手", "稳健"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "csi300_enhanced",
        "name": "csi300_enhanced",
        "display_name": "沪深300增强策略",
        "short_description": "以宽基指数为基准，尝试用温和增强方式观察超额收益。",
        "beginner_explanation": "它更接近指数投资体验，适合先理解系统如何工作。",
        "category": "指数增强策略",
        "risk_level": "low",
        "suitable_market": "bull",
        "suitable_user": "beginner",
        "strategy_type": "index_enhancement",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["指数增强", "新手", "沪深300"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "sector_rotation",
        "name": "sector_rotation",
        "display_name": "行业轮动策略",
        "short_description": "比较不同行业的阶段表现，用模拟方式观察轮动节奏。",
        "beginner_explanation": "它适合想理解市场热点切换的人，波动会更明显。",
        "category": "行业轮动策略",
        "risk_level": "high",
        "suitable_market": "liquidity_driven",
        "suitable_user": "advanced",
        "strategy_type": "sector_rotation",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["行业轮动", "进阶", "趋势"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "semiconductor_momentum",
        "name": "semiconductor_momentum",
        "display_name": "半导体动量策略",
        "short_description": "观察半导体板块中的动量机会，波动和回撤可能更大。",
        "beginner_explanation": "它更激进，只适合用模拟交易先观察风险。",
        "category": "动量趋势策略",
        "risk_level": "high",
        "suitable_market": "bull",
        "suitable_user": "advanced",
        "strategy_type": "momentum",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["半导体", "动量", "高波动"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "index_trend",
        "name": "index_trend",
        "display_name": "指数趋势策略",
        "short_description": "观察指数级别的趋势状态，适合理解牛熊转换。",
        "beginner_explanation": "它不挑个股，主要看市场整体趋势是否友好。",
        "category": "动量趋势策略",
        "risk_level": "medium",
        "suitable_market": "bull",
        "suitable_user": "beginner",
        "strategy_type": "index_enhancement",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["趋势", "指数", "新手"],
        "updated_at_placeholder": "local-demo",
    },
    {
        "strategy_id": "blue_chip_value",
        "name": "blue_chip_value",
        "display_name": "蓝筹低估值策略",
        "short_description": "关注更成熟公司的低估值机会，适合稳健模拟观察。",
        "beginner_explanation": "它偏稳，不追求很高弹性，更适合先做模拟组合体验。",
        "category": "低估值策略",
        "risk_level": "low",
        "suitable_market": "sideways",
        "suitable_user": "steady",
        "strategy_type": "value",
        "backtest_available": True,
        "paper_trading_available": True,
        "real_trading_available": False,
        "code_visible_by_default": False,
        "tags": ["低估值", "蓝筹", "稳健"],
        "updated_at_placeholder": "local-demo",
    },
]


def build_strategy_catalog() -> list[dict]:
    return [dict(item) for item in CATALOG]


def list_strategy_categories() -> list[str]:
    return list(CATEGORIES)


def list_recommended_strategies() -> list[dict]:
    ids = {"csi300_enhanced", "dividend_low_vol", "blue_chip_value"}
    return [item for item in build_strategy_catalog() if item["strategy_id"] in ids]


def list_beginner_strategies() -> list[dict]:
    return [item for item in build_strategy_catalog() if item["suitable_user"] == "beginner"]


def list_advanced_strategies() -> list[dict]:
    return [item for item in build_strategy_catalog() if item["suitable_user"] == "advanced"]
