services:
  ui:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: streamlit run app/main.py --server.address=0.0.0.0 --server.port=8501
    env_file:
      - .env.example
    ports:
      - "8501:8501"
    volumes:
      - ../data:/app/data

  api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    command: uvicorn src.api.v2.server:app --host 0.0.0.0 --port 8000
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
